export * from './page-template.catalog'
export * from './page-template.types'
export { default as DashboardTemplate } from './dashboard/DashboardTemplate.vue'
export { default as DashboardWorkspaceTemplate } from './dashboard/DashboardWorkspaceTemplate.vue'
export { default as CrudListTemplate } from './crud/CrudListTemplate.vue'
export { default as EditorWorkbenchTemplate } from './editor/EditorWorkbenchTemplate.vue'
export { default as ProfileTemplate } from './account/ProfileTemplate.vue'
export { default as PlaceholderTemplate } from './system/PlaceholderTemplate.vue'
export { default as ErrorNotFoundTemplate } from './system/ErrorNotFoundTemplate.vue'