import { createTemplateCatalogEntry, type TemplateCatalogEntry } from '../contracts'

export const pageTemplateCatalog: TemplateCatalogEntry[] = [
  createTemplateCatalogEntry({
    id: 'page-dashboard',
    area: 'page',
    title: 'Dashboard Template',
    description: 'Dashboard page archetype with cards, charts and responsive sections.',
    targetPath: 'src/templates/pages/dashboard/DashboardTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/pages/PipelinePage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'page-dashboard-workspace',
    area: 'page',
    title: 'Dashboard Workspace Template',
    description: 'Generic enterprise dashboard workspace with control panel, KPI cards and workflow lanes.',
    targetPath: 'src/templates/pages/dashboard/DashboardWorkspaceTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/pages/PipelinePage.vue + https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/search/control_panel',
  }),
  createTemplateCatalogEntry({
    id: 'page-crud-list',
    area: 'page',
    title: 'CRUD List Template',
    description: 'Generic CRUD list template with search, filters, table/cards modes, row actions and bulk flows.',
    targetPath: 'src/templates/pages/crud/CrudListTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/pages/WikiPage.vue + https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/views/list',
  }),
  createTemplateCatalogEntry({
    id: 'page-editor-workbench',
    area: 'page',
    title: 'Editor Workbench Template',
    description: 'Enterprise visual editor template with command bars, widget palette, ruler/grid canvas, right tools rail and status strips.',
    targetPath: 'src/templates/pages/editor/EditorWorkbenchTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference + user-validated BoldReports-style editing shell baseline',
  }),
  createTemplateCatalogEntry({
    id: 'page-profile',
    area: 'page',
    title: 'Profile Template',
    description: 'Profile page archetype with account and preferences surfaces.',
    targetPath: 'src/templates/pages/account/ProfileTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/pages/ProfilePage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'page-placeholder',
    area: 'page',
    title: 'Placeholder Template',
    description: 'Placeholder page archetype for pending modules with status messaging.',
    targetPath: 'src/templates/pages/system/PlaceholderTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/pages/PlaceholderPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'page-not-found',
    area: 'page',
    title: 'Error Not Found Template',
    description: 'Not found page archetype with safe navigation recovery actions.',
    targetPath: 'src/templates/pages/system/ErrorNotFoundTemplate.vue',
    status: 'in_progress',
    customizableScopes: ['theme', 'content', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/pages/ErrorNotFound.vue',
  }),
]