import { createTemplateCatalogEntry, type TemplateCatalogEntry } from '../contracts'

export const scaffoldTemplateCatalog: TemplateCatalogEntry[] = [
  createTemplateCatalogEntry({
    id: 'scaffold-auth-store',
    area: 'scaffolding',
    title: 'Auth Store Scaffold Template',
    description: 'Framework-agnostic auth state scaffold with user, token, initials, persistence hooks and a useAuth composable factory.',
    targetPath: 'src/templates/scaffolding/auth-store.template.ts',
    status: 'ready',
    customizableScopes: ['behavior', 'data', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/auth/stores/authStore.ts + .temp/reference/src/modules/auth/composables/useAuth.ts',
  }),
  createTemplateCatalogEntry({
    id: 'scaffold-router',
    area: 'scaffolding',
    title: 'Router Scaffold Template',
    description: 'Template-aware route registration scaffold for layout/page templates.',
    targetPath: 'src/templates/scaffolding/router-template.ts',
    status: 'ready',
    customizableScopes: ['navigation', 'behavior', 'testing'],
    sourceReferencePath: '.temp/reference/src/router/routes.ts',
  }),
  createTemplateCatalogEntry({
    id: 'scaffold-menu',
    area: 'scaffolding',
    title: 'Menu Constants Scaffold Template',
    description: 'Template-ready menu contract scaffold for horizontal and vertical navigation.',
    targetPath: 'src/templates/scaffolding/menu.constants.template.ts',
    status: 'ready',
    customizableScopes: ['navigation', 'content', 'testing'],
    sourceReferencePath: '.temp/reference/src/shared/constants/menu.constants.ts',
  }),
  createTemplateCatalogEntry({
    id: 'scaffold-layout-store',
    area: 'scaffolding',
    title: 'Layout State Scaffold Template',
    description: 'Template state scaffold for drawer/header/menu mode behavior.',
    targetPath: 'src/templates/scaffolding/layout-store.template.ts',
    status: 'ready',
    customizableScopes: ['behavior', 'data', 'testing'],
    sourceReferencePath: '.temp/reference/src/stores/layout-store.ts',
  }),
  createTemplateCatalogEntry({
    id: 'scaffold-notification',
    area: 'scaffolding',
    title: 'Notification Scaffold Template',
    description: 'Template-safe notification bridge scaffold for reusable page/feature templates.',
    targetPath: 'src/templates/scaffolding/notification.template.ts',
    status: 'ready',
    customizableScopes: ['behavior', 'content', 'testing'],
    sourceReferencePath: '.temp/reference/src/shared/utils/notification.ts',
  }),
]