import { createTemplateCatalogEntry, type TemplateCatalogEntry } from '../contracts'

export const featureTemplateCatalog: TemplateCatalogEntry[] = [
  createTemplateCatalogEntry({
    id: 'feature-auth-login',
    area: 'feature',
    title: 'Login Template',
    description: 'Authentication login screen template with branded split layout support.',
    targetPath: 'src/templates/features/auth/LoginTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/auth/pages/LoginPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki',
    area: 'feature',
    title: 'Wiki Template',
    description: 'Knowledge base template with categories, filters, list/grid modes and summary.',
    targetPath: 'src/templates/features/wiki/WikiTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/pages/WikiPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki-chat-page',
    area: 'feature',
    title: 'Wiki Chat Page Template',
    description: 'Full page chat experience template for assistant interactions.',
    targetPath: 'src/templates/features/wiki/WikiChatTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/pages/WikiChatPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki-chat-drawer',
    area: 'feature',
    title: 'Wiki Chat Drawer Template',
    description: 'Floating chat drawer template with contextual prompts and sources.',
    targetPath: 'src/templates/features/wiki/WikiChatDrawerTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/components/ChatDrawer.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-command-center',
    area: 'feature',
    title: 'Enterprise Command Center Template',
    description: 'Operational command-center template with incident alerts, activity feed and service health.',
    targetPath: 'src/templates/features/enterprise/EnterpriseCommandCenterTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/search/control_panel + https://mui.com/material-ui/getting-started/templates/dashboard/',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-approval-queue',
    area: 'feature',
    title: 'Approval Queue Template',
    description: 'Enterprise approval queue template with decision actions and bulk workflow operations.',
    targetPath: 'src/templates/features/enterprise/ApprovalQueueTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/views/list + .temp/reference/src/modules/wiki/pages/WikiPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-audit-timeline',
    area: 'feature',
    title: 'Audit Timeline Template',
    description: 'Audit and compliance timeline template with searchable governance events.',
    targetPath: 'src/templates/features/enterprise/AuditTimelineTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/views/form + https://www.atlassian.com/software/jira/features/kanban-boards',
  }),
]