import { createTemplateCatalogEntry, type TemplateCatalogEntry } from '../contracts'

export const featureTemplateCatalog: TemplateCatalogEntry[] = [
  createTemplateCatalogEntry({
    id: 'feature-auth-login',
    area: 'feature',
    title: 'Login Template',
    description: 'Authentication login screen template with branded split layout support.',
    targetPath: 'src/templates/features/auth/LoginTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/auth/pages/LoginPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki',
    area: 'feature',
    title: 'Wiki Template',
    description: 'Knowledge base template with categories, filters, list/grid modes and summary.',
    targetPath: 'src/templates/features/wiki/WikiTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/pages/WikiPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki-chat-page',
    area: 'feature',
    title: 'Wiki Chat Page Template',
    description: 'Full page chat experience template for assistant interactions.',
    targetPath: 'src/templates/features/wiki/WikiChatTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/pages/WikiChatPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-wiki-chat-drawer',
    area: 'feature',
    title: 'Wiki Chat Drawer Template',
    description: 'Floating chat drawer template with contextual prompts and sources.',
    targetPath: 'src/templates/features/wiki/WikiChatDrawerTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: '.temp/reference/src/modules/wiki/components/ChatDrawer.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-command-center',
    area: 'feature',
    title: 'Enterprise Command Center Template',
    description: 'Operational command-center template with incident alerts, activity feed and service health.',
    targetPath: 'src/templates/features/enterprise/EnterpriseCommandCenterTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/search/control_panel + https://mui.com/material-ui/getting-started/templates/dashboard/',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-approval-queue',
    area: 'feature',
    title: 'Approval Queue Template',
    description: 'Enterprise approval queue template with decision actions and bulk workflow operations.',
    targetPath: 'src/templates/features/enterprise/ApprovalQueueTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/views/list + .temp/reference/src/modules/wiki/pages/WikiPage.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-enterprise-audit-timeline',
    area: 'feature',
    title: 'Audit Timeline Template',
    description: 'Audit and compliance timeline template with searchable governance events.',
    targetPath: 'src/templates/features/enterprise/AuditTimelineTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'https://github.com/odoo/odoo/tree/18.0/addons/web/static/src/views/form + https://www.atlassian.com/software/jira/features/kanban-boards',
  }),
  createTemplateCatalogEntry({
    id: 'feature-reference-report-manager',
    area: 'feature',
    title: 'Reference Report Manager Template',
    description: 'Approved report catalog surface with reusable explorer panel, report metadata and whitelabel summary.',
    targetPath: 'src/templates/features/reference-system/ReferenceReportManagerTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: 'planning/reference/edit.png',
  }),
  createTemplateCatalogEntry({
    id: 'feature-reference-report-designer',
    area: 'feature',
    title: 'Reference Report Designer Template',
    description: 'Approved report designer workspace that composes the catalog panel with the reusable editor workbench shell.',
    targetPath: 'src/templates/features/reference-system/ReferenceReportDesignerTemplate.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'navigation', 'a11y', 'testing'],
    sourceReferencePath: 'planning/reference/edit.png + planning/reference/layout-reference-system.md',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-authoring-workbench',
    area: 'feature',
    title: 'CMS Authoring Workbench',
    description: 'CMS authoring shell that composes all module surfaces inside an EditorWorkbenchTemplate wrapper.',
    targetPath: 'src/templates/features/cms/authoring/CmsAuthoringWorkbench.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-settings-surface',
    area: 'feature',
    title: 'CMS Settings Module Surface',
    description: 'CMS white-label settings workspace: branding, typography, layout, colors, menu, and topbar configuration.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsSettingsModuleSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-blocks-surface',
    area: 'feature',
    title: 'CMS Blocks Module Surface',
    description: 'CMS block builder workspace: section palette, block drag-and-drop, reusable blocks, and block preset library.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsBlocksModuleSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-media-surface',
    area: 'feature',
    title: 'CMS Media Module Surface',
    description: 'CMS media asset management workspace with upload, tagging, and asset picker.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsMediaModuleSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-pages-surface',
    area: 'feature',
    title: 'CMS Pages Module Surface',
    description: 'CMS page authoring workspace with content models, locale coverage, and entity usage tracking.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsPagesModuleSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-pages-preview-surface',
    area: 'feature',
    title: 'CMS Pages Preview Surface',
    description: 'CMS live preview surface for inspecting pages in desktop and mobile viewports.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsPagesPreviewSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
  createTemplateCatalogEntry({
    id: 'feature-cms-releases-surface',
    area: 'feature',
    title: 'CMS Releases Module Surface',
    description: 'CMS release governance workspace: publish gates, diff views, and release history.',
    targetPath: 'src/templates/features/cms/authoring/modules/CmsReleasesModuleSurface.vue',
    status: 'ready',
    customizableScopes: ['theme', 'content', 'data', 'behavior', 'a11y', 'testing'],
    sourceReferencePath: 'landing-page/CmsApp.vue',
  }),
]