export * from './feature-template.catalog'
export * from './cms'
export { default as LoginTemplate } from './auth/LoginTemplate.vue'
export * from './enterprise'
export * from './reference-system'
export { default as WikiChatDrawerTemplate } from './wiki/WikiChatDrawerTemplate.vue'
export { default as WikiChatTemplate } from './wiki/WikiChatTemplate.vue'
export { default as WikiTemplate } from './wiki/WikiTemplate.vue'
export * from './wiki/wiki-template.types'