/**
 * Src/components/layout/app shell config module.
 */

import type { AppShellConfig, AppShellTheme } from './app-shell.types'
import { semanticColors } from '../../config/colors/semantic.config'
import { resolveAppShellTheme } from './app-shell.theme'

const APP_SHELL_COLOR_TOKENS = {
  white: 'var(--ntk-bg-card)',
  secondarySurface: 'var(--ntk-bg-hover)',
  textInverse: 'var(--ntk-text-inverse)',
  neutral500: 'var(--ntk-text-secondary)',
  neutral600: 'var(--ntk-text-muted)',
  neutral700: 'var(--ntk-text-primary)',
  neutral300: 'var(--ntk-border-dark)',
  neutral200: 'var(--ntk-text-muted)',
  neutral100: 'var(--ntk-border-light)',
  accent: 'var(--ntk-primary)',
  danger: `var(--semantic-error, ${semanticColors.errorPrimary})`,
  success: `var(--semantic-success, ${semanticColors.successPrimary})`,
  warning: `var(--semantic-warning, ${semanticColors.warningPrimary})`,
  info: `var(--semantic-info, ${semanticColors.infoPrimary})`,
  pageText: 'var(--ntk-text-primary)',
} as const

const APP_SHELL_EFFECT_TOKENS = {
  shellBackground: 'var(--ntk-gradient-subtle, var(--ntk-gradient-hero))',
  headerShadow: 'var(--ntk-shadow-sm)',
  drawerShadow: 'var(--ntk-shadow-sm)',
  searchBorder: 'var(--ntk-border-input)',
  searchBorderHover: 'var(--ntk-border-input-hover)',
  actionBackground: 'transparent',
  actionHoverBackground: 'var(--ntk-bg-hover)',
  groupCaptionMiniBackground: 'var(--ntk-bg-hover)',
  itemHoverBackground: 'var(--ntk-bg-hover)',
  itemActiveBackground: 'var(--ntk-bg-active)',
  drawerFooterShadow: 'var(--ntk-shadow-sm)',
} as const

const APP_SHELL_LANDING_COLOR_TOKENS = {
  absoluteWhite: 'var(--ntk-landing-absolute-white, var(--ntk-text-on-accent, var(--ntk-bg-card)))',
  brandPrimary: 'var(--ntk-landing-brand-primary, var(--ntk-primary))',
  brandPrimaryDark: 'var(--ntk-landing-brand-primary-dark, var(--ntk-primary-dark, var(--ntk-primary)))',
  brandPrimaryLight: 'var(--ntk-landing-brand-primary-light, var(--ntk-primary-light, var(--ntk-bg-hover)))',
  brandSecondary: 'var(--ntk-landing-brand-secondary, var(--ntk-text-secondary))',
  gray900: 'var(--ntk-landing-gray-900, var(--ntk-text-primary))',
  gray800: 'var(--ntk-landing-gray-800, color-mix(in srgb, var(--ntk-text-primary) 92%, var(--ntk-bg-primary)))',
  gray700: 'var(--ntk-landing-gray-700, color-mix(in srgb, var(--ntk-text-primary) 78%, var(--ntk-bg-primary)))',
  gray600: 'var(--ntk-landing-gray-600, var(--ntk-text-secondary))',
  gray500: 'var(--ntk-landing-gray-500, var(--ntk-text-muted))',
  gray400: 'var(--ntk-landing-gray-400, color-mix(in srgb, var(--ntk-text-muted) 72%, var(--ntk-bg-card)))',
  gray300: 'var(--ntk-landing-gray-300, var(--ntk-border-color))',
  gray200: 'var(--ntk-landing-gray-200, var(--ntk-border-light, var(--ntk-border-color)))',
  gray100: 'var(--ntk-landing-gray-100, var(--ntk-bg-tertiary))',
  gray50: 'var(--ntk-landing-gray-50, var(--ntk-bg-secondary))',
  white: 'var(--ntk-landing-white, var(--ntk-bg-card))',
  black: 'var(--ntk-landing-black, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  sectionBgPrimary: 'var(--ntk-landing-section-bg-primary, var(--ntk-bg-primary))',
  sectionBgSecondary: 'var(--ntk-landing-section-bg-secondary, var(--ntk-bg-secondary))',
  sectionBgDark: 'var(--ntk-landing-section-bg-dark, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  sectionBgPrimaryDark: 'var(--ntk-landing-section-bg-primary-dark, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  sectionBgSecondaryDark: 'var(--ntk-landing-section-bg-secondary-dark, var(--ntk-bg-tertiary))',
  sectionBgDarkDark: 'var(--ntk-landing-section-bg-dark-dark, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  ghBgCanvas: 'var(--ntk-landing-gh-bg-canvas, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  ghBgSubtle: 'var(--ntk-landing-gh-bg-subtle, var(--ntk-bg-tertiary))',
  ghBgMuted: 'var(--ntk-landing-gh-bg-muted, var(--ntk-bg-hover))',
  ghBorderDefault: 'var(--ntk-landing-gh-border-default, var(--ntk-border-color))',
  ghFgDefault: 'var(--ntk-landing-gh-fg-default, var(--ntk-text-primary))',
  ghFgMuted: 'var(--ntk-landing-gh-fg-muted, var(--ntk-text-secondary))',
  ghFgSubtle: 'var(--ntk-landing-gh-fg-subtle, var(--ntk-text-muted))',
  ghAccent: 'var(--ntk-landing-gh-accent, var(--ntk-accent, var(--ntk-primary)))',
  ghAccentEmphasis: 'var(--ntk-landing-gh-accent-emphasis, var(--ntk-primary-dark, var(--ntk-accent)))',
  ghAccentHover: 'var(--ntk-landing-gh-accent-hover, var(--ntk-accent-hover, var(--ntk-primary)))',
  ghAccentSubtle: 'var(--ntk-landing-gh-accent-subtle, var(--ntk-accent-soft, var(--ntk-bg-hover)))',
  sharedDarkBg: 'var(--ntk-landing-shared-dark-bg, var(--ntk-bg-dark, var(--ntk-text-primary)))',
  sharedDarkSurface: 'var(--ntk-landing-shared-dark-surface, var(--ntk-bg-tertiary))',
  sharedDarkSurfaceMuted: 'var(--ntk-landing-shared-dark-surface-muted, var(--ntk-bg-hover))',
  sharedDarkBorder: 'var(--ntk-landing-shared-dark-border, var(--ntk-border-color))',
  sharedDarkText: 'var(--ntk-landing-shared-dark-text, var(--ntk-text-primary))',
  sharedDarkTextMuted: 'var(--ntk-landing-shared-dark-text-muted, var(--ntk-text-secondary))',
  sharedDarkAccent: 'var(--ntk-landing-shared-dark-accent, var(--ntk-accent, var(--ntk-primary)))',
  codeKeyword: 'var(--ntk-landing-code-keyword, var(--semantic-info-primary, var(--ntk-info)))',
  codeString: 'var(--ntk-landing-code-string, var(--semantic-success-primary, var(--ntk-success)))',
  codeComponent: 'var(--ntk-landing-code-component, var(--ntk-primary-light, var(--ntk-primary)))',
  codeProp: 'var(--ntk-landing-code-prop, var(--semantic-warning-primary, var(--ntk-warning)))',
  codeComment: 'var(--ntk-landing-code-comment, var(--ntk-text-muted))',
  themeGradientStart: 'var(--ntk-landing-theme-gradient-start, var(--ntk-primary-gradient-start, var(--ntk-primary)))',
  themeGradientEnd: 'var(--ntk-landing-theme-gradient-end, var(--ntk-primary-gradient-end, var(--ntk-accent)))',
  heroHighlight1: 'var(--ntk-landing-hero-highlight-1, var(--ntk-bg-secondary))',
  heroHighlight2: 'var(--ntk-landing-hero-highlight-2, var(--ntk-border-light, var(--ntk-border-color)))',
  heroHighlight3: 'var(--ntk-landing-hero-highlight-3, var(--ntk-text-muted))',
  heroHighlight4: 'var(--ntk-landing-hero-highlight-4, var(--ntk-border-color))',
  heroHighlight5: 'var(--ntk-landing-hero-highlight-5, var(--ntk-bg-hover))',
} as const

const APP_SHELL_BASE_THEME: AppShellTheme = {
  fontFamily: 'var(--ntk-font-family)',
  fontFamilyDisplay: 'var(--ntk-font-family-display)',
  fontStyleBase: 'normal',
  fontWeightRegular: 'var(--ntk-font-weight-normal)',
  fontWeightMedium: 'var(--ntk-font-weight-medium)',
  fontWeightSemibold: 'var(--ntk-font-weight-semibold)',
  fontWeightBold: 'var(--ntk-font-weight-bold)',
  fontSizeBase: '0.95rem',
  fontSizeTitle: '1rem',
  fontSizeTitleApp: '1.18rem',
  fontSizeBrandTitle: '0.9rem',
  fontSizeBrandSubtitle: '0.72rem',
  fontSizeItemLabel: '13px',
  fontSizeItemCaption: '11px',
  fontSizeGroupCaption: '0.68rem',
  fontSizeGroupCaptionMini: '0.62rem',
  letterSpacingGroupCaption: '0.08em',
  letterSpacingGroupCaptionMini: '0.06em',
  lineHeightBrandText: '1.1',
  lineHeightItemLabel: '1.25',
  lineHeightItemCaption: '1.2',
  borderWidth: '1px',
  menuSlotWidth: '30px',
  searchWidth: '320px',
  searchControlHeight: '36px',
  searchPrependPaddingRight: '12px',
  drawerHeaderMinHeight: '64px',
  brandLogoSize: '34px',
  groupCaptionMinHeight: '24px',
  groupCaptionPadding: '0.45rem 1rem 0.25rem',
  groupCaptionMiniPadding: '0.45rem 0',
  groupCaptionMiniMinWidth: '34px',
  groupCaptionMiniHeight: '18px',
  groupCaptionMiniHorizontalPadding: '0.35rem',
  groupCaptionMiniRadius: '999px',
  itemMinHeight: '52px',
  itemIconSize: '22px',
  itemHoverTranslateX: '4px',
  itemActiveBorderWidth: '4px',
  drawerScrollPaddingBottom: '80px',
  workspaceMaxWidth: '1280px',
  viewportHeight: '100vh',
  compactBreakpoint: '500',
  compactPagePadding: 'var(--ntk-shell-space-md)',
  compactWorkspaceCardPadding: 'var(--ntk-shell-space-md)',
  layoutBreakpointLg: '1280',
  layoutBreakpointMd: '1024',
  cmsLayoutBreakpointLg: '1280',
  cmsLayoutBreakpointMd: '1024',
  miniItemMarginRight: '12px',
  miniItemAvatarMinWidth: '28px',
  radiusSm: '6px',
  radiusMd: '8px',
  radiusLg: '10px',
  radiusItem: '0 28px 28px 0',
  spacingXs: '0.25rem',
  spacingSm: '0.5rem',
  spacingMd: '0.75rem',
  spacingLg: '1rem',
  transitionFast: 'var(--ntk-transition-base)',
  titleSeparatorSize: 'calc(var(--ntk-shell-font-size-title-app) + var(--ntk-shell-space-xs))',
  userAvatarSize: 'calc(var(--ntk-shell-search-control-height) - (var(--ntk-shell-space-xs) * 2))',
  headerBlur: 'blur(calc(var(--ntk-shell-space-sm) * 2))',
  actionHoverTranslateY: 'calc(var(--ntk-shell-space-xs) * -0.5)',
  itemCaptionOffset: 'calc(var(--ntk-shell-space-xs) * 0.6)',
  headerZIndex: '3000',
  drawerZIndex: '2000',
  groupSeparatorOpacity: '0.12',
  badgePulseScale: '1.1',
  shellBackground: APP_SHELL_EFFECT_TOKENS.shellBackground,
  headerBackground: APP_SHELL_COLOR_TOKENS.white,
  headerTextColor: APP_SHELL_COLOR_TOKENS.neutral500,
  headerShadow: APP_SHELL_EFFECT_TOKENS.headerShadow,
  toolbarButtonColor: APP_SHELL_COLOR_TOKENS.neutral500,
  titleAppColor: APP_SHELL_COLOR_TOKENS.neutral700,
  titleTextColor: APP_SHELL_COLOR_TOKENS.neutral600,
  titleSeparatorColor: APP_SHELL_COLOR_TOKENS.neutral300,
  drawerBackground: APP_SHELL_COLOR_TOKENS.white,
  drawerTextColor: APP_SHELL_COLOR_TOKENS.neutral500,
  drawerShadow: APP_SHELL_EFFECT_TOKENS.drawerShadow,
  drawerFooterBackground: APP_SHELL_COLOR_TOKENS.white,
  dividerColor: APP_SHELL_COLOR_TOKENS.neutral100,
  searchBackground: APP_SHELL_COLOR_TOKENS.secondarySurface,
  searchTextColor: APP_SHELL_COLOR_TOKENS.neutral700,
  searchIconColor: APP_SHELL_COLOR_TOKENS.neutral600,
  searchBorder: APP_SHELL_EFFECT_TOKENS.searchBorder,
  searchBorderHover: APP_SHELL_EFFECT_TOKENS.searchBorderHover,
  focusColor: APP_SHELL_COLOR_TOKENS.accent,
  actionBackground: APP_SHELL_EFFECT_TOKENS.actionBackground,
  actionHoverBackground: APP_SHELL_EFFECT_TOKENS.actionHoverBackground,
  // Keep the default equal to error, but as a concrete color to avoid implicit coupling.
  notificationBadgeColor: semanticColors.errorPrimary,
  notificationBadgeTextColor: APP_SHELL_COLOR_TOKENS.textInverse,
  notificationIconColor: APP_SHELL_COLOR_TOKENS.neutral500,
  notificationSuccessColor: APP_SHELL_COLOR_TOKENS.success,
  notificationWarningColor: APP_SHELL_COLOR_TOKENS.warning,
  notificationErrorColor: APP_SHELL_COLOR_TOKENS.danger,
  notificationInfoColor: APP_SHELL_COLOR_TOKENS.info,
  notificationSuccessTextColor: APP_SHELL_COLOR_TOKENS.textInverse,
  notificationWarningTextColor: APP_SHELL_COLOR_TOKENS.neutral700,
  notificationErrorTextColor: APP_SHELL_COLOR_TOKENS.textInverse,
  notificationInfoTextColor: APP_SHELL_COLOR_TOKENS.textInverse,
  brandTitleColor: APP_SHELL_COLOR_TOKENS.neutral700,
  brandSubtitleColor: APP_SHELL_COLOR_TOKENS.neutral600,
  groupCaptionColor: APP_SHELL_COLOR_TOKENS.neutral200,
  groupCaptionMiniBackground: APP_SHELL_EFFECT_TOKENS.groupCaptionMiniBackground,
  itemTextColor: APP_SHELL_COLOR_TOKENS.neutral500,
  itemHoverBackground: APP_SHELL_EFFECT_TOKENS.itemHoverBackground,
  itemHoverColor: APP_SHELL_COLOR_TOKENS.accent,
  itemIconColor: APP_SHELL_COLOR_TOKENS.neutral500,
  itemIconHoverColor: APP_SHELL_COLOR_TOKENS.accent,
  itemActiveBackground: APP_SHELL_EFFECT_TOKENS.itemActiveBackground,
  itemActiveColor: APP_SHELL_COLOR_TOKENS.accent,
  drawerFooterShadow: APP_SHELL_EFFECT_TOKENS.drawerFooterShadow,
  pageBackground: APP_SHELL_COLOR_TOKENS.secondarySurface,
  pageTextColor: APP_SHELL_COLOR_TOKENS.pageText,
  landingAbsoluteWhite: APP_SHELL_LANDING_COLOR_TOKENS.absoluteWhite,
  landingFontSize2xs: '0.65rem',
  landingFontSizeXsTight: '0.7rem',
  landingFontSizeSmTight: '0.8125rem',
  landingFontSizeSmPlus: '0.9375rem',
  landingFontSizeMdPlus: '1.03rem',
  landingFontSizeLgPlus: '1.06rem',
  landingFontSizeXlPlus: '1.14rem',
  landingFontSizeDisplaySm: '1.65rem',
  landingFontSizeDisplayMd: '1.7rem',
  landingFontSizeDisplayLg: '1.85rem',
  landingFontSizeDisplayXl: '1.95rem',
  landingFontSizeDisplay2xl: '2rem',
  landingFontSizeDisplay3xl: '2.15rem',
  landingSpaceXs: '0.25rem',
  landingSpaceSm: '0.5rem',
  landingSpaceMd: '1rem',
  landingSpaceLg: '1.5rem',
  landingSpaceXl: '2rem',
  landingSpace2xl: '3rem',
  landingSpace3xl: '4rem',
  landingRadiusXs: '6px',
  landingRadiusSm: '8px',
  landingRadiusMd: '12px',
  landingRadiusLg: '16px',
  landingRadiusXl: '20px',
  landingRadiusRound: '100px',
  landingRadiusPill: '999px',
  landingShadowHeader: '0 2px 8px color-mix(in srgb, var(--gray-900) 30%, transparent)',
  landingShadowEmphasis: '0 8px 24px color-mix(in srgb, var(--gray-900) 30%, transparent)',
  landingShadowTopbarScrolled: '0 10px 24px color-mix(in srgb, var(--gray-900) 22%, transparent)',
  landingShadowCodeFrame: '0 18px 36px color-mix(in srgb, var(--landing-black) 32%, transparent)',
  landingShadowCodeFrameHover: '0 22px 44px color-mix(in srgb, var(--gray-900) 34%, transparent)',
  landingEasingStandard: 'cubic-bezier(0.4, 0, 0.2, 1)',
  landingTransitionFast: '220ms var(--easing-standard)',
  landingTransitionNormal: '350ms var(--easing-standard)',
  landingTransitionSlow: '500ms var(--easing-standard)',
  landingRevealDistance: '52px',
  landingRevealDuration: '760ms',
  landingRevealThreshold: '0.18',
  landingRevealRootMargin: '0px 0px -10% 0px',
  landingImageHoverZoomScale: '1.045',
  landingImageHoverZoomDuration: '620ms',
  landingImageHoverZoomEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
  landingComponentCardHoverScale: '1.018',
  landingComponentCardHoverLift: '-3px',
  landingComponentCardAccentWidth: '4px',
  landingComponentCardAccentOpacity: '0.95',
  landingComponentCardAccentEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
  landingCodeBlockHoverScale: '1.015',
  landingTopbarEnterDuration: '520ms',
  landingTopbarEnterOffset: '18px',
  landingPulseDotDuration: '2s',
  landingPulseDotEasing: 'ease-in-out',
  landingFloatDuration: '4s',
  landingFloatEasing: 'ease-in-out',
  landingFloatDelaySm: '0.2s',
  landingFloatDelayMd: '0.3s',
  landingFloatDelayLg: '0.6s',
  landingFloatDelayXl: '0.9s',
  landingLayoutContainIntrinsicSize: '900px',
  landingLayoutContainerMaxWidth: '1200px',
  landingLayoutTopbarBackdropBlur: '8px',
  landingLayoutTopbarActionSize: '40px',
  landingLayoutTopbarIndicatorOffset: '-0.35rem',
  landingLayoutTopbarIndicatorHeight: '3px',
  landingLayoutButtonGap: '0.5rem',
  landingLayoutButtonPadding: '0.85rem',
  landingLayoutButtonHoverLift: '-1px',
  landingLayoutHeroPaddingTop: '160px',
  landingLayoutHeroPaddingBottom: '100px',
  landingLayoutHeroPaddingTopMobile: '120px',
  landingLayoutHeroPaddingBottomMobile: '60px',
  landingLayoutHeroOrbSize: '800px',
  landingLayoutHeroTitleClamp: 'clamp(3.2rem, 5vw, 3.6rem)',
  landingLayoutSectionTitleClamp: 'clamp(2.3rem, 3.8vw, 2.65rem)',
  landingLayoutHeroTextMaxWidth: '500px',
  landingLayoutHeroVisualMaxWidth: '700px',
  landingLayoutSectionHeaderMaxWidth: '600px',
  landingLayoutMediaMaxWidth: '500px',
  landingLayoutComposablesVisualPaddingTop: '120px',
  landingLayoutChartHeight: '200px',
  landingLayoutChartLabelOffset: '-24px',
  landingLayoutDrawerWidth: '300px',
  landingLayoutFooterDescriptionMaxWidth: '300px',
  landingLayoutHeroVisualTabletMaxWidth: '600px',
  landingLayoutCompactGridMaxWidth: '400px',
  landingLayoutStatMinWidthMobile: '80px',
  landingLayoutMobileMenuButtonPadding: '8px',
  landingLayoutFloatingButtonRight: '1rem',
  landingLayoutFloatingButtonBottom: '1rem',
  landingLayoutFloatingButtonPaddingY: '0.625rem',
  landingLayoutFloatingButtonPaddingX: '0.875rem',
  landingLayoutPulseDotSize: '8px',
  landingLayoutCodeDotSize: '12px',
  landingLayoutMetricIconSize: '48px',
  landingLayoutMiniIconSize: '24px',
  landingLayoutThemeBadgeSize: '80px',
  landingLayoutFloatAmplitude: '-8px',
  landingLayoutBodyLineHeight: '1.6',
  landingLayoutBorderThin: '1px',
  landingLayoutHeaderZIndex: '100',
  landingLayoutDrawerZIndex: '1000',
  landingLayoutOverlayZIndex: '999',
  landingLayoutFloatingButtonZIndex: '1100',
  landingLayoutHeroOrbTop: '-50%',
  landingLayoutHeroOrbRight: '-20%',
  landingLayoutHeroBadgeLetterSpacing: '0.5px',
  landingLayoutSectionBadgeLetterSpacing: '0.05em',
  landingLayoutNavLineHeight: '1',
  landingLayoutHeroTitleLineHeight: '1.1',
  landingLayoutFeatureTextLineHeight: '1.6',
  landingLayoutCtaSubtitleLineHeight: '1.5',
  landingLayoutCodeLineHeight: '1.7',
  landingLayoutFooterDescriptionLineHeight: '1.6',
  landingLayoutFooterHeadingLineHeight: '1.2',
  landingLayoutFooterLinkLineHeight: '1.35',
  landingLayoutFooterLinkTitleLetterSpacing: '0.05em',
  landingLayoutFloatingButtonLetterSpacing: '0.01em',
  landingLayoutThemeBadgeHoverScale: '1.08',
  landingLayoutChartBarHoverOpacity: '0.8',
  landingLayoutDrawerShadow: '-4px 0 20px color-mix(in srgb, var(--gray-900) 10%, transparent)',
  landingBreakpointLg: '1024',
  landingBreakpointMd: '768',
  landingBreakpointSm: '480',
  landingBrandPrimary: APP_SHELL_LANDING_COLOR_TOKENS.brandPrimary,
  landingBrandPrimaryDark: APP_SHELL_LANDING_COLOR_TOKENS.brandPrimaryDark,
  landingBrandPrimaryLight: APP_SHELL_LANDING_COLOR_TOKENS.brandPrimaryLight,
  landingBrandSecondary: APP_SHELL_LANDING_COLOR_TOKENS.brandSecondary,
  landingGray900: APP_SHELL_LANDING_COLOR_TOKENS.gray900,
  landingGray800: APP_SHELL_LANDING_COLOR_TOKENS.gray800,
  landingGray700: APP_SHELL_LANDING_COLOR_TOKENS.gray700,
  landingGray600: APP_SHELL_LANDING_COLOR_TOKENS.gray600,
  landingGray500: APP_SHELL_LANDING_COLOR_TOKENS.gray500,
  landingGray400: APP_SHELL_LANDING_COLOR_TOKENS.gray400,
  landingGray300: APP_SHELL_LANDING_COLOR_TOKENS.gray300,
  landingGray200: APP_SHELL_LANDING_COLOR_TOKENS.gray200,
  landingGray100: APP_SHELL_LANDING_COLOR_TOKENS.gray100,
  landingGray50: APP_SHELL_LANDING_COLOR_TOKENS.gray50,
  landingWhite: APP_SHELL_LANDING_COLOR_TOKENS.white,
  landingSectionBgPrimary: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgPrimary,
  landingSectionBgSecondary: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgSecondary,
  landingSectionBgDark: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgDark,
  landingSectionBgPrimaryDark: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgPrimaryDark,
  landingSectionBgSecondaryDark: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgSecondaryDark,
  landingSectionBgDarkDark: APP_SHELL_LANDING_COLOR_TOKENS.sectionBgDarkDark,
  landingGhBgCanvas: APP_SHELL_LANDING_COLOR_TOKENS.ghBgCanvas,
  landingGhBgSubtle: APP_SHELL_LANDING_COLOR_TOKENS.ghBgSubtle,
  landingGhBgMuted: APP_SHELL_LANDING_COLOR_TOKENS.ghBgMuted,
  landingGhBorderDefault: APP_SHELL_LANDING_COLOR_TOKENS.ghBorderDefault,
  landingGhFgDefault: APP_SHELL_LANDING_COLOR_TOKENS.ghFgDefault,
  landingGhFgMuted: APP_SHELL_LANDING_COLOR_TOKENS.ghFgMuted,
  landingGhFgSubtle: APP_SHELL_LANDING_COLOR_TOKENS.ghFgSubtle,
  landingGhAccent: APP_SHELL_LANDING_COLOR_TOKENS.ghAccent,
  landingGhAccentEmphasis: APP_SHELL_LANDING_COLOR_TOKENS.ghAccentEmphasis,
  landingGhAccentHover: APP_SHELL_LANDING_COLOR_TOKENS.ghAccentHover,
  landingGhAccentSubtle: APP_SHELL_LANDING_COLOR_TOKENS.ghAccentSubtle,
  landingSharedDarkBg: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkBg,
  landingSharedDarkSurface: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkSurface,
  landingSharedDarkSurfaceMuted: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkSurfaceMuted,
  landingSharedDarkBorder: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkBorder,
  landingSharedDarkText: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkText,
  landingSharedDarkTextMuted: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkTextMuted,
  landingSharedDarkAccent: APP_SHELL_LANDING_COLOR_TOKENS.sharedDarkAccent,
  landingCodeKeyword: APP_SHELL_LANDING_COLOR_TOKENS.codeKeyword,
  landingCodeString: APP_SHELL_LANDING_COLOR_TOKENS.codeString,
  landingCodeComponent: APP_SHELL_LANDING_COLOR_TOKENS.codeComponent,
  landingCodeProp: APP_SHELL_LANDING_COLOR_TOKENS.codeProp,
  landingCodeComment: APP_SHELL_LANDING_COLOR_TOKENS.codeComment,
  landingThemeGradientStart: APP_SHELL_LANDING_COLOR_TOKENS.themeGradientStart,
  landingThemeGradientEnd: APP_SHELL_LANDING_COLOR_TOKENS.themeGradientEnd,
  landingHeroHighlight1: APP_SHELL_LANDING_COLOR_TOKENS.heroHighlight1,
  landingHeroHighlight2: APP_SHELL_LANDING_COLOR_TOKENS.heroHighlight2,
  landingHeroHighlight3: APP_SHELL_LANDING_COLOR_TOKENS.heroHighlight3,
  landingHeroHighlight4: APP_SHELL_LANDING_COLOR_TOKENS.heroHighlight4,
  landingHeroHighlight5: APP_SHELL_LANDING_COLOR_TOKENS.heroHighlight5,
  landingBlack: APP_SHELL_LANDING_COLOR_TOKENS.black,
}

export const APP_SHELL_DEFAULT_THEME: AppShellTheme = resolveAppShellTheme(APP_SHELL_BASE_THEME)

export const SENTINELA_LIKE_THEME: AppShellTheme = {
  ...APP_SHELL_DEFAULT_THEME,
}

export const APP_SHELL_DEFAULTS: AppShellConfig = {
  appName: 'NetToolsKit',
  appSubtitle: 'NTK Reference',
  brandLogo: '/favicon.png',
  brandLogoAlt: 'NTK',
  menuIcon: 'menu',
  menuAriaLabel: 'Toggle menu',
  navGroups: [],
  items: [],
  activeItem: '',
  searchValue: '',
  searchPlaceholder: 'Search module',
  showSearch: true,
  showGroupCaptions: true,
  toolbarActions: [],
  theme: APP_SHELL_DEFAULT_THEME,
  showNotifications: true,
  notificationsTooltip: 'Notifications',
  notificationCount: 0,
  showUserAvatar: true,
  userAvatar: '',
  userTooltip: 'Account',
  collapsible: true,
  collapseLabel: 'Collapse menu',
  expandLabel: 'Expand menu',
  drawerWidth: 200,
  miniWidth: 64,
  breakpoint: 1024,
  headerHeight: 64,
  defaultDrawerOpen: true,
  defaultMini: false,
}

/**
 * Handles merge shell config.
 */
function mergeShellConfig(base: AppShellConfig, partial: Partial<AppShellConfig>): AppShellConfig {
  return {
    ...base,
    ...partial,
    navGroups: partial.navGroups ?? base.navGroups,
    items: partial.items ?? base.items,
    toolbarActions: partial.toolbarActions ?? base.toolbarActions,
    theme: {
      ...(base.theme ?? APP_SHELL_DEFAULT_THEME),
      ...(partial.theme ?? {}),
    },
  }
}

/**
 * Creates app shell config.
 */
export function createAppShellConfig(partial: Partial<AppShellConfig> = {}): AppShellConfig {
  return mergeShellConfig(APP_SHELL_DEFAULTS, partial)
}

/**
 * Handles sentinela like preset.
 */
export function sentinelaLikePreset(partial: Partial<AppShellConfig> = {}): AppShellConfig {
  return createAppShellConfig(partial)
}
