/**
 * Src/components/layout/app shell types module.
 */

export interface AppShellGroup {
  id: string
  label: string
}

export interface AppShellItem {
  id: string
  group: string
  label: string
  icon: string
  caption?: string
  description?: string
  badge?: string | number
  badgeColor?: string
  badgeTextColor?: string
}

export interface AppShellAction {
  id: string
  icon?: string
  label?: string
  tooltip?: string
  href?: string
  external?: boolean
  color?: string
  textColor?: string
  badge?: string | number
  badgeColor?: string
  badgeTextColor?: string
  flat?: boolean
  dense?: boolean
  round?: boolean
  unelevated?: boolean
  outline?: boolean
  noCaps?: boolean
  showLabel?: boolean
  className?: string
}

export interface AppShellTheme {
  fontFamily?: string
  fontFamilyDisplay?: string
  fontStyleBase?: string
  fontWeightRegular?: string
  fontWeightMedium?: string
  fontWeightSemibold?: string
  fontWeightBold?: string
  fontSizeBase?: string
  fontSizeTitle?: string
  fontSizeTitleApp?: string
  fontSizeBrandTitle?: string
  fontSizeBrandSubtitle?: string
  fontSizeItemLabel?: string
  fontSizeItemCaption?: string
  fontSizeGroupCaption?: string
  fontSizeGroupCaptionMini?: string
  letterSpacingGroupCaption?: string
  letterSpacingGroupCaptionMini?: string
  lineHeightBrandText?: string
  lineHeightItemLabel?: string
  lineHeightItemCaption?: string
  borderWidth?: string
  menuSlotWidth?: string
  searchWidth?: string
  searchControlHeight?: string
  searchPrependPaddingRight?: string
  drawerHeaderMinHeight?: string
  brandLogoSize?: string
  groupCaptionMinHeight?: string
  groupCaptionPadding?: string
  groupCaptionMiniPadding?: string
  groupCaptionMiniMinWidth?: string
  groupCaptionMiniHeight?: string
  groupCaptionMiniHorizontalPadding?: string
  groupCaptionMiniRadius?: string
  itemMinHeight?: string
  itemIconSize?: string
  itemHoverTranslateX?: string
  itemActiveBorderWidth?: string
  drawerScrollPaddingBottom?: string
  workspaceMaxWidth?: string
  viewportHeight?: string
  compactBreakpoint?: string
  compactPagePadding?: string
  compactWorkspaceCardPadding?: string
  layoutBreakpointLg?: string
  layoutBreakpointMd?: string
  cmsLayoutBreakpointLg?: string
  cmsLayoutBreakpointMd?: string
  miniItemMarginRight?: string
  miniItemAvatarMinWidth?: string
  radiusSm?: string
  radiusMd?: string
  radiusLg?: string
  radiusItem?: string
  spacingXs?: string
  spacingSm?: string
  spacingMd?: string
  spacingLg?: string
  transitionFast?: string
  titleSeparatorSize?: string
  userAvatarSize?: string
  headerBlur?: string
  actionHoverTranslateY?: string
  itemCaptionOffset?: string
  headerZIndex?: string
  drawerZIndex?: string
  groupSeparatorOpacity?: string
  badgePulseScale?: string
  shellBackground?: string
  headerBackground?: string
  headerTextColor?: string
  headerShadow?: string
  toolbarButtonColor?: string
  titleAppColor?: string
  titleTextColor?: string
  titleSeparatorColor?: string
  drawerShadow?: string
  drawerBackground?: string
  drawerTextColor?: string
  drawerFooterBackground?: string
  dividerColor?: string
  searchBackground?: string
  searchTextColor?: string
  searchIconColor?: string
  searchBorder?: string
  searchBorderHover?: string
  focusColor?: string
  actionBackground?: string
  actionHoverBackground?: string
  notificationBadgeColor?: string
  notificationBadgeTextColor?: string
  notificationIconColor?: string
  notificationSuccessColor?: string
  notificationWarningColor?: string
  notificationErrorColor?: string
  notificationInfoColor?: string
  notificationSuccessTextColor?: string
  notificationWarningTextColor?: string
  notificationErrorTextColor?: string
  notificationInfoTextColor?: string
  brandTitleColor?: string
  brandSubtitleColor?: string
  groupCaptionColor?: string
  groupCaptionMiniBackground?: string
  itemTextColor?: string
  itemHoverBackground?: string
  itemHoverColor?: string
  itemIconColor?: string
  itemIconHoverColor?: string
  itemActiveBackground?: string
  itemActiveColor?: string
  drawerFooterShadow?: string
  pageBackground?: string
  pageTextColor?: string
  landingAbsoluteWhite?: string
  landingFontSize2xs?: string
  landingFontSizeXsTight?: string
  landingFontSizeSmTight?: string
  landingFontSizeSmPlus?: string
  landingFontSizeMdPlus?: string
  landingFontSizeLgPlus?: string
  landingFontSizeXlPlus?: string
  landingFontSizeDisplaySm?: string
  landingFontSizeDisplayMd?: string
  landingFontSizeDisplayLg?: string
  landingFontSizeDisplayXl?: string
  landingFontSizeDisplay2xl?: string
  landingFontSizeDisplay3xl?: string
  landingSpaceXs?: string
  landingSpaceSm?: string
  landingSpaceMd?: string
  landingSpaceLg?: string
  landingSpaceXl?: string
  landingSpace2xl?: string
  landingSpace3xl?: string
  landingRadiusXs?: string
  landingRadiusSm?: string
  landingRadiusMd?: string
  landingRadiusLg?: string
  landingRadiusXl?: string
  landingRadiusRound?: string
  landingRadiusPill?: string
  landingShadowHeader?: string
  landingShadowEmphasis?: string
  landingShadowTopbarScrolled?: string
  landingShadowCodeFrame?: string
  landingShadowCodeFrameHover?: string
  landingEasingStandard?: string
  landingTransitionFast?: string
  landingTransitionNormal?: string
  landingTransitionSlow?: string
  landingRevealDistance?: string
  landingRevealDuration?: string
  landingRevealThreshold?: string
  landingRevealRootMargin?: string
  landingImageHoverZoomScale?: string
  landingImageHoverZoomDuration?: string
  landingImageHoverZoomEasing?: string
  landingComponentCardHoverScale?: string
  landingComponentCardHoverLift?: string
  landingComponentCardAccentWidth?: string
  landingComponentCardAccentOpacity?: string
  landingComponentCardAccentEasing?: string
  landingCodeBlockHoverScale?: string
  landingTopbarEnterDuration?: string
  landingTopbarEnterOffset?: string
  landingPulseDotDuration?: string
  landingPulseDotEasing?: string
  landingFloatDuration?: string
  landingFloatEasing?: string
  landingFloatDelaySm?: string
  landingFloatDelayMd?: string
  landingFloatDelayLg?: string
  landingFloatDelayXl?: string
  landingLayoutContainIntrinsicSize?: string
  landingLayoutContainerMaxWidth?: string
  landingLayoutTopbarBackdropBlur?: string
  landingLayoutTopbarActionSize?: string
  landingLayoutTopbarIndicatorOffset?: string
  landingLayoutTopbarIndicatorHeight?: string
  landingLayoutButtonGap?: string
  landingLayoutButtonPadding?: string
  landingLayoutButtonHoverLift?: string
  landingLayoutHeroPaddingTop?: string
  landingLayoutHeroPaddingBottom?: string
  landingLayoutHeroPaddingTopMobile?: string
  landingLayoutHeroPaddingBottomMobile?: string
  landingLayoutHeroOrbSize?: string
  landingLayoutHeroTitleClamp?: string
  landingLayoutSectionTitleClamp?: string
  landingLayoutHeroTextMaxWidth?: string
  landingLayoutHeroVisualMaxWidth?: string
  landingLayoutSectionHeaderMaxWidth?: string
  landingLayoutMediaMaxWidth?: string
  landingLayoutComposablesVisualPaddingTop?: string
  landingLayoutChartHeight?: string
  landingLayoutChartLabelOffset?: string
  landingLayoutDrawerWidth?: string
  landingLayoutFooterDescriptionMaxWidth?: string
  landingLayoutHeroVisualTabletMaxWidth?: string
  landingLayoutCompactGridMaxWidth?: string
  landingLayoutStatMinWidthMobile?: string
  landingLayoutMobileMenuButtonPadding?: string
  landingLayoutFloatingButtonRight?: string
  landingLayoutFloatingButtonBottom?: string
  landingLayoutFloatingButtonPaddingY?: string
  landingLayoutFloatingButtonPaddingX?: string
  landingLayoutPulseDotSize?: string
  landingLayoutCodeDotSize?: string
  landingLayoutMetricIconSize?: string
  landingLayoutMiniIconSize?: string
  landingLayoutThemeBadgeSize?: string
  landingLayoutFloatAmplitude?: string
  landingLayoutBodyLineHeight?: string
  landingLayoutBorderThin?: string
  landingLayoutHeaderZIndex?: string
  landingLayoutDrawerZIndex?: string
  landingLayoutOverlayZIndex?: string
  landingLayoutFloatingButtonZIndex?: string
  landingLayoutHeroOrbTop?: string
  landingLayoutHeroOrbRight?: string
  landingLayoutHeroBadgeLetterSpacing?: string
  landingLayoutSectionBadgeLetterSpacing?: string
  landingLayoutNavLineHeight?: string
  landingLayoutHeroTitleLineHeight?: string
  landingLayoutFeatureTextLineHeight?: string
  landingLayoutCtaSubtitleLineHeight?: string
  landingLayoutCodeLineHeight?: string
  landingLayoutFooterDescriptionLineHeight?: string
  landingLayoutFooterHeadingLineHeight?: string
  landingLayoutFooterLinkLineHeight?: string
  landingLayoutFooterLinkTitleLetterSpacing?: string
  landingLayoutFloatingButtonLetterSpacing?: string
  landingLayoutThemeBadgeHoverScale?: string
  landingLayoutChartBarHoverOpacity?: string
  landingLayoutDrawerShadow?: string
  landingBreakpointLg?: string
  landingBreakpointMd?: string
  landingBreakpointSm?: string
  landingBrandPrimary?: string
  landingBrandPrimaryDark?: string
  landingBrandPrimaryLight?: string
  landingBrandSecondary?: string
  landingGray900?: string
  landingGray800?: string
  landingGray700?: string
  landingGray600?: string
  landingGray500?: string
  landingGray400?: string
  landingGray300?: string
  landingGray200?: string
  landingGray100?: string
  landingGray50?: string
  landingWhite?: string
  landingSectionBgPrimary?: string
  landingSectionBgSecondary?: string
  landingSectionBgDark?: string
  landingSectionBgPrimaryDark?: string
  landingSectionBgSecondaryDark?: string
  landingSectionBgDarkDark?: string
  landingGhBgCanvas?: string
  landingGhBgSubtle?: string
  landingGhBgMuted?: string
  landingGhBorderDefault?: string
  landingGhFgDefault?: string
  landingGhFgMuted?: string
  landingGhFgSubtle?: string
  landingGhAccent?: string
  landingGhAccentEmphasis?: string
  landingGhAccentHover?: string
  landingGhAccentSubtle?: string
  landingSharedDarkBg?: string
  landingSharedDarkSurface?: string
  landingSharedDarkSurfaceMuted?: string
  landingSharedDarkBorder?: string
  landingSharedDarkText?: string
  landingSharedDarkTextMuted?: string
  landingSharedDarkAccent?: string
  landingCodeKeyword?: string
  landingCodeString?: string
  landingCodeComponent?: string
  landingCodeProp?: string
  landingCodeComment?: string
  landingThemeGradientStart?: string
  landingThemeGradientEnd?: string
  landingHeroHighlight1?: string
  landingHeroHighlight2?: string
  landingHeroHighlight3?: string
  landingHeroHighlight4?: string
  landingHeroHighlight5?: string
  landingBlack?: string
}

export interface AppShellConfig {
  appName: string
  appSubtitle: string
  brandLogo: string
  brandLogoAlt: string
  menuIcon: string
  menuAriaLabel: string
  navGroups: AppShellGroup[]
  items: AppShellItem[]
  activeItem: string
  searchValue: string
  searchPlaceholder: string
  showSearch: boolean
  showGroupCaptions: boolean
  toolbarActions: AppShellAction[]
  theme: AppShellTheme
  showNotifications: boolean
  notificationsTooltip: string
  notificationCount: number
  showUserAvatar: boolean
  userAvatar: string
  userTooltip: string
  collapsible: boolean
  collapseLabel: string
  expandLabel: string
  drawerWidth: number
  miniWidth: number
  breakpoint: number
  headerHeight: number
  defaultDrawerOpen: boolean
  defaultMini: boolean
}

export interface AppShellTelemetryEvent {
  type: 'navigation-select' | 'search-update' | 'toolbar-action' | 'menu-toggle'
  component: 'NtkAppShell'
  payload: Record<string, unknown>
  timestamp: string
}

export interface NtkAppShellProps {
  appName?: string
  appSubtitle?: string
  brandLogo?: string
  brandLogoAlt?: string
  menuIcon?: string
  menuAriaLabel?: string
  navGroups?: AppShellGroup[]
  items?: AppShellItem[]
  activeItem?: string
  searchValue?: string
  searchPlaceholder?: string
  showSearch?: boolean
  showGroupCaptions?: boolean
  toolbarActions?: AppShellAction[]
  theme?: AppShellTheme
  showNotifications?: boolean
  notificationsTooltip?: string
  notificationCount?: number
  showUserAvatar?: boolean
  userAvatar?: string
  userTooltip?: string
  collapsible?: boolean
  collapseLabel?: string
  expandLabel?: string
  drawerWidth?: number
  miniWidth?: number
  breakpoint?: number
  headerHeight?: number
  defaultDrawerOpen?: boolean
  defaultMini?: boolean
  searchAriaLabel?: string
  navigationAriaLabel?: string
  navigationItemsAriaLabel?: string
  toolbarAriaLabel?: string
  notificationsAriaLabel?: string
  userAriaLabel?: string
  itemAriaLabelPrefix?: string
  actionAriaLabelPrefix?: string
}

export interface NtkAppShellEmits {
  (e: 'update:active-item', value: string): void
  (e: 'update:search-value', value: string): void
  (e: 'item-click', value: AppShellItem): void
  (e: 'notifications-click'): void
  (e: 'user-click'): void
  (e: 'toolbar-action', value: AppShellAction): void
  (e: 'toggle-menu', value: { mini: boolean; open: boolean }): void
  (e: 'telemetry', value: AppShellTelemetryEvent): void
}