export { default as DsButton } from './DsButton.vue'
export { default as DsCard } from './DsCard.vue'
export { default as DsInput } from './DsInput.vue'
export { default as DsSelect } from './DsSelect.vue'
export { default as DsTable } from './DsTable.vue'
export { default as DsPage } from './DsPage.vue'
export { default as DsSection } from './DsSection.vue'